site_name: Small World Analytics

repo_name: brown5628/small-world-analytics-site
repo_url: https://github.com/brown5628/small-world-analytics-site

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/brown5628
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/brown5628
      
theme:
  name: material
  logo: images/planet-sharp.svg
  palette:
    scheme: default
    primary: white
    accent: blue
  features:
    - tabs

nav:
  - Home: index.md

  - Forecasting:
    - Introduction: forecasting-notebooks/forecasting.md
    - Notebooks:
      - ACB confirmed before election: forecasting-notebooks/acb_confirmation.ipynb
  - Quantified Self:
    - Introduction: quantified-self/quantified-self.md
    - Personal Tracker: http://personal-tracker.smallworldanalytics.com
    - Personal Kanban Metrics: http://agile-metrics.smallworldanalytics.com



plugins:
  - mknotebooks