site_name: Small World Analytics

repo_name: brown5628/small-world-analytics-site
repo_url: https://github.com/brown5628/small-world-analytics-site

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/brown5628
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/brown5628

theme:
  name: material
  logo: images/planet-sharp.svg
  palette:
    scheme: default
    primary: black
    accent: blue

nav:
  - Home: index.md
  - Personal Tracker: http://personal-tracker.smallworldanalytics.com
  - Personal Kanban Metrics: http://agile-metrics.smallworldanalytics.com